Update etmv4.c
hwangcc23/ptm2human pull request #6
Opened 2019-07-29 02:04 UTC by jeremyng123

in ihi0064F etm4.0-etm4.4 architecture spectification (pg 6-282), Atom Format 6 Instruction trace packet only permits count values from 0b00000 to 0b10100 (0 to 20)

2019-07-30 14:13 UTC, hwangcc23 commented on etmv4.c
> +        LOGE("Invalid COUNT in a ATOM format 6 packet\n");
Typo here
"an ATOM"

2019-07-30 14:13 UTC, hwangcc23 commented on etmv4.c
> +        return 1;
Should return -1 to indicate the error.

2019-07-30 14:15 UTC, hwangcc23 commented on etmv4.c
> +// changes masks values for atom_format_1-4: jeremyng123
This change (to add the comment line) is not needed.

2019-07-30 14:25 UTC, hwangcc23 requested changes
Please help check comments, squash them, and resend the PR.
Thanks.

2019-07-30 14:42 UTC, jeremyng123 commented
I have resolved your comments. Please verify the changes :)

2019-07-30 14:46 UTC, hwangcc23 commented
OK for me.
Please squash all commits into one commit. Thanks.
Reference: https://github.com/wprig/wprig/wiki/How-to-squash-commits

2019-07-31 03:37 UTC, jeremyng123 commented
Hi, I didn't exactly squash the commits because there were some issues. but i have redid the PR to only have 1 commit. there shouldn't be any difference in the changes as discussed.

2019-07-31 15:41 UTC, hwangcc23 commented
Some of your changes (fix-typo) are not squashed into your final patch. To avoid micro-management, I will merge your patch directly, and fix other problems later directly.
Thanks for your contribution.

2019-07-31 15:41 UTC, merged